# Generated by Django 3.2.5 on 2021-07-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),  # verbose name은 화면에 뭐라고 보여지게 하고 싶은지
                ('name', models.CharField(max_length=100)),  # 글자 수 제한O
                ('desc', models.TextField(blank=True)),  # 공백 허용 글자수 제한X
                ('price', models.PositiveIntegerField()),
                # auto_now_add는 최종 저장 시각, auto_now는 수정 저장될 때 마다.
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
