# Generated by Django 3.2.5 on 2021-07-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [  # 리스트로 나열. 데이터베이스에 어떤 변화를 가하는 오퍼레이션들. forward적용. backward적용.
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),  # verbose name은 화면에 뭐라고 보여지게 하고 싶은지
                ('name', models.CharField(max_length=100)),  # 글자 수 제한O
                ('desc', models.TextField(blank=True)),  # 공백 허용 글자수 제한X
                ('price', models.PositiveIntegerField()),
                # auto_now_add는 최종 저장 시각, auto_now는 수정 저장될 때 마다.
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

# 모델 만들고 makemigrations로 파일 생성.
# 생성된 migration 파일 확인, sql확인. 제대로 안됐으면 수정하거나 제거해서 다시 하거나
# 제대로 잘 만들어졌으면 migrate로 적용. migrate하지 않은 파일은 언제든 삭제 가능. 한 파일을 삭제하면 꼬인다.
